## install the libary by using this command pip install numpy

In [116]:
! pip install numpy 


[notice] A new release of pip is available: 24.1.1 -> 24.2
[notice] To update, run: C:\Users\i\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip


In [1]:
import numpy as np                          # import as a keyword and numpy as a libary and jo as h vo keyword and np is sort form of numpy
print("import sucess")

import sucess


In [2]:
lst= [23,54,65,76,87,78,5,566,4,]
print(type(lst))

<class 'list'>


In [ ]:
arr=np.array(lst)    #  list ko array me convert karne ke liya array function ka use kiya h 
arr

array([ 23,  54,  65,  76,  87,  78,   5, 566,   4])

In [3]:
a=[12,4,5,6,7,8]
print(a)

[12, 4, 5, 6, 7, 8]


In [4]:
arr=np.array(a)        #  array me convert karne ke liya 
arr

array([12,  4,  5,  6,  7,  8])

In [5]:
print(type(arr))            # type check karne ke liya 

<class 'numpy.ndarray'>


In [6]:
aee=np.array([22,4,5,76,9,9,0])  #   array me slicing karne ka liya 
arr
print(arr[0:5])

[12  4  5  6  7]


In [7]:
arr=np.arange(1,21)       # jese range function kam karta h vase arange function kam karta h 
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
arr=np.zeros(10) #      zeros 
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
arr=np.ones(10)    # ones 
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
arr=np.linspace(1,10,5)          # 1 h jo starting point h  10 h vo maximium point h or jo 5 h vo counting h 
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [12]:
arr=np.arange(0,30).reshape(10,3)         # reshape function array ko reshape karta h 10 h vo row h or 3 column h 
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
arr=np.arange(0,10).reshape(5,2)          # 5 row and 2 columns 
arr


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [14]:
arr=np.random.randint(1,5,9)      #  randit function create random arrray 
arr

array([2, 4, 4, 3, 4, 2, 1, 4, 2], dtype=int32)

In [15]:
arr=np.random.randint(1,5,(7,5))      # 1 se le kar 5 tak numbers aaiyege 
                                       # 7 row and 5 column 
arr

array([[4, 4, 2, 2, 3],
       [1, 1, 2, 1, 3],
       [4, 3, 4, 1, 3],
       [4, 4, 1, 1, 3],
       [1, 1, 1, 4, 4],
       [2, 1, 2, 3, 1],
       [3, 3, 2, 2, 2]], dtype=int32)

In [17]:
np.random.random(5)        # koi bhi random number create ho jaiyege jitne hum ko chiye

array([0.57679053, 0.66720001, 0.99942403, 0.62242285, 0.56817864])

In [19]:
lst= [23,45,6,7,8,9,96]
arr=np.array(lst)                 # list ko array me convertt ki hui h 
print(arr)


[23 45  6  7  8  9 96]


In [134]:
np.array(range(1,20))           #  range function 1 ,20 tak counting karta h 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [135]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [136]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [137]:
np.arange(1,20)           # arange function range ki thara hi kam karta hhh

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [138]:
np.arange(0,20).reshape(5,4)        # 0 se le kar 20 tak number de ga or 5 row and 4 column 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [139]:
np.random.randint(1,10,8)     #  1  first starting point  10  ending point 8 jitne element chiye 

array([8, 8, 8, 4, 5, 9, 1, 8], dtype=int32)

In [140]:
np.random.randint(1,10,(9,6))          #  1 se le kar 10 tak number  9 row and 6 column 

array([[9, 9, 1, 5, 8, 9],
       [1, 4, 8, 8, 9, 9],
       [4, 3, 3, 9, 2, 8],
       [2, 8, 5, 5, 6, 1],
       [9, 4, 9, 7, 1, 5],
       [9, 2, 1, 4, 2, 7],
       [9, 4, 9, 1, 7, 4],
       [2, 8, 5, 9, 1, 5],
       [1, 1, 9, 3, 5, 5]], dtype=int32)

In [141]:
np.random.random()          # koi bhi random number de de ga 

0.8084330506526023

In [142]:
np.random.random(10)     #  koi bhi 10 random number de de ga 

array([0.92999053, 0.53464797, 0.47539334, 0.0653286 , 0.01298303,
       0.5402162 , 0.06376995, 0.44182692, 0.93821916, 0.99100304])

In [143]:
np.random.random((4,5))   # koi bhi random number de de ga 4 row and 5 column me 


array([[0.02441244, 0.71645215, 0.05425396, 0.09440937, 0.19102534],
       [0.63119698, 0.26035076, 0.74907596, 0.82622581, 0.38395115],
       [0.69278546, 0.73215431, 0.39525922, 0.45377247, 0.20308885],
       [0.3008165 , 0.01474829, 0.34175442, 0.35474391, 0.71453444]])

In [21]:
arr1=np.arange(60).reshape(12,5)     #   60 tak number chalega  12 row and 5 column me  
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [22]:
print(arr1)
arr1.shape    # find the shape   #  kitni row h or kitni column h 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


(12, 5)

In [23]:
arr1.ndim      # number of dimanction in array 

2

In [24]:
arr1.size        # find the size of array 

60

In [25]:
arr1.dtype  

dtype('int64')

In [26]:
arr1.flatten()    # 2 d array convert into 1 d array 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [150]:
arr1.ravel()                  #  2 d array convert into 1 d array 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [151]:
lst=[[1,3,4,],[4,5,6]]          # 2 d list 
lst

[[1, 3, 4], [4, 5, 6]]

In [152]:
arr1=np.array(lst)         # list ko array me convert karta h 
arr1


array([[1, 3, 4],
       [4, 5, 6]])

In [153]:
arr1.shape             # 2 row h or 3 column h 

(2, 3)

In [154]:
arr1.size         # mean of size kitne element h 

6

In [155]:
arr1.dtype

dtype('int64')

In [156]:
arr1.ndim          # kon sa array h   

2

In [157]:
arr1.shape

(2, 3)

In [158]:
# 2 row and 3 column


In [159]:
arr1.T.shape

(3, 2)

In [160]:
# how to access the elememt from 1d and 2 d array



In [30]:
arr=np.arange(60).reshape(12,5)            # arange function jitni counting chiya utni likh de ga ,
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [162]:
# print(arr[14])       # indexing 

In [31]:
arr[0:7]     # slicing

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [34]:
print(arr[0:8]) 
      #  0 se start h 22 tak chalega  
# arr

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [165]:
# print(arr[10:110:10])
# arr

In [166]:
# arr1=arr.reshape(12,5)      # reshape me 12 column or 5 row h 
# arr1

In [36]:
arr1[1]


array([5, 6, 7, 8, 9])

In [168]:
#  28, 29
#  41, 42, 43, 44],
#        [45, 46, 47
#         59

In [37]:
arr1[2:4,0]

array([10, 15])

In [38]:
arr1[7:9,2]

array([37, 42])

In [39]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [40]:
arr1[11:4]

array([], shape=(0, 5), dtype=int64)

In [41]:
arr[-1,-4]         # -1 is determine last row and -4 is determine last 4 element 

array([213, 214, 215])

In [42]:
arr[0,3]=100           # 0 row and 3 number par jo element h us ki gajha 100 jodna h 

In [43]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [176]:
arr

array([[  0,   1,   2, 100,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [44]:
arr[6:9,2]

array([], shape=(0, 3), dtype=int64)

In [45]:
arr[9:12,3]

array([], shape=(0, 3), dtype=int64)

In [46]:
arr[9:12,4]
# arr.shape
# arr.ndim


array([], shape=(0, 3), dtype=int64)

In [47]:
15*5

75

In [48]:
75*3

225

In [49]:
arr=np.arange(225).reshape(5,15,3)  # 5 tables 3 columns 15 rows
                                

In [50]:
arr.shape    

(5, 15, 3)

In [51]:
arr.ndim

3

In [52]:
arr.dtype

dtype('int64')

In [186]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

## 3 D array 

In [187]:
arr=np.arange(225).reshape(5,15,3)        # 3 D array 225 tak chalega 5 table 15 row 3 column 
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)


3
(5, 15, 3)
int64
225


In [188]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [53]:
arr[0,1]  
         # 0 is the determine table and 2 is the determine row of table 

array([3, 4, 5])

In [54]:
arr[0:1]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [55]:
arr[0:5,14,2]          # table ka starting point 0 h ending point 5 h 
                        # 14 no ki row h or 2 no ki column h 

array([ 44,  89, 134, 179, 224])

In [56]:
arr [4,14,2]          #  first 4 ko to table  and 14 row and 2 column 

np.int64(224)

In [193]:
arr[4,0:14,2]

array([182, 185, 188, 191, 194, 197, 200, 203, 206, 209, 212, 215, 218,
       221])

In [194]:
arr[0:5,14]

array([[ 42,  43,  44],
       [ 87,  88,  89],
       [132, 133, 134],
       [177, 178, 179],
       [222, 223, 224]])

In [195]:
arr[0:5,:,1]

array([[  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
         40,  43],
       [ 46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,  79,  82,
         85,  88],
       [ 91,  94,  97, 100, 103, 106, 109, 112, 115, 118, 121, 124, 127,
        130, 133],
       [136, 139, 142, 145, 148, 151, 154, 157, 160, 163, 166, 169, 172,
        175, 178],
       [181, 184, 187, 190, 193, 196, 199, 202, 205, 208, 211, 214, 217,
        220, 223]])

In [196]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [197]:
arr[0:5,2:4]

array([[[  6,   7,   8],
        [  9,  10,  11]],

       [[ 51,  52,  53],
        [ 54,  55,  56]],

       [[ 96,  97,  98],
        [ 99, 100, 101]],

       [[141, 142, 143],
        [144, 145, 146]],

       [[186, 187, 188],
        [189, 190, 191]]])

In [198]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [199]:
arr[0:5,13:15,1:3]

array([[[ 40,  41],
        [ 43,  44]],

       [[ 85,  86],
        [ 88,  89]],

       [[130, 131],
        [133, 134]],

       [[175, 176],
        [178, 179]],

       [[220, 221],
        [223, 224]]])

In [200]:
a=np.array()
arr

TypeError: array() missing required argument 'object' (pos 0)

In [380]:
a=[12,35,56,7,7,8]

In [381]:
a=np.array(a)
a

array([12, 35, 56,  7,  7,  8])

In [97]:
np.array(a)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [99]:
arr[2:5,0:14,0:3]

array([[[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 119],
        [120, 121, 122],
        [123, 124, 125],
        [126, 127, 128],
        [129, 130, 131]],

       [[135, 136, 137],
        [138, 139, 140],
        [141, 142, 143],
        [144, 145, 146],
        [147, 148, 149],
        [150, 151, 152],
        [153, 154, 155],
        [156, 157, 158],
        [159, 160, 161],
        [162, 163, 164],
        [165, 166, 167],
        [168, 169, 170],
        [171, 172, 173],
        [174, 175, 176]],

       [[180, 181, 182],
        [183, 184, 185],
        [186, 187, 188],
        [189, 190, 191],
        [192, 193, 194],
        [195, 196, 197],
        [198, 199, 200],
        [201, 202, 203],
        [204, 205, 206],
        [207, 208, 209],
        [210, 211, 212],
        [213, 214, 21

In [100]:
arr[arr>100]

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
       192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
       205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217,
       218, 219, 220, 221, 222, 223, 224])

In [91]:
arr[4,3]

array([189, 190, 191])

In [93]:
arr[0:5,0:15,2]

array([[  2,   5,   8,  11,  14,  17,  20,  23,  26,  29,  32,  35,  38,
         41,  44],
       [ 47,  50,  53,  56,  59,  62,  65,  68,  71,  74,  77,  80,  83,
         86,  89],
       [ 92,  95,  98, 101, 104, 107, 110, 113, 116, 119, 122, 125, 128,
        131, 134],
       [137, 140, 143, 146, 149, 152, 155, 158, 161, 164, 167, 170, 173,
        176, 179],
       [182, 185, 188, 191, 194, 197, 200, 203, 206, 209, 212, 215, 218,
        221, 224]])

In [ ]:
# arthmatic operator

In [206]:
c=[12,34,56,7,788,43,32]
d=[21,342,54,56,76,8,7]


In [207]:
c=np.array(c)
c
# np.dtype
# print(type(c))

array([ 12,  34,  56,   7, 788,  43,  32])

In [208]:
d=np.array(d)
d

array([ 21, 342,  54,  56,  76,   8,   7])

In [209]:
c+d

array([ 33, 376, 110,  63, 864,  51,  39])

In [210]:
c-d

array([  -9, -308,    2,  -49,  712,   35,   25])

In [211]:
c*d

array([  252, 11628,  3024,   392, 59888,   344,   224])

In [213]:
c/d

array([ 0.57142857,  0.0994152 ,  1.03703704,  0.125     , 10.36842105,
        5.375     ,  4.57142857])

In [214]:
c//d

array([ 0,  0,  1,  0, 10,  5,  4])